[package]
name = "openstreet"
version = "0.0.1"
authors = ["Hernawan Fa'iz Abdillah <hernawan.faiz.abdillah@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [lib]
# name = "openstreet"
# crate-type = ["cdylib"]

[lib]
name = "openstreet2"
crate-type = ["cdylib"]
path = "src/map.rs"

[dependencies]
fast_paths = "0.2.0"
fnv = "1.0.6"
osm-xml = "0.6.2"

[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module"]
